### ISSUE TITLE
How to migrate drupal to Platform.sh?

### ISSUE THREAD

**Issue by uzair001** [platformsh/platformsh-examples#26]
Hello.
I am very new to platform.sh.I need to migrate drupal to platform.sh.
But i have no idea how can i do this.

Can anyone please tell me how can achieve this.

Thanks.

**Comment by arosboro** [comment]
There is documentation at https://docs.platform.sh/toolstacks/php/symfony/migrate-existing-site/?highlight=migrate

**Comment by GuGuss** [comment]
Follow up on here #27 and #28.
