### ISSUE TITLE
question about session save path

### ISSUE THREAD

**Issue by OskarStark** [platformsh/platformsh-examples#64]
when i look at this example:
https://github.com/platformsh/platformsh-examples/blob/symfony/todo-mvc-full/app/config/parameters_platform.php

this line:
```php
# Store session into /tmp.
ini_set('session.save_path', '/tmp/sessions');
```

is only executed when a relationship exists

is this correct?
or should it be moved to the top of this example?

**Comment by OriPekelman** [comment]
We encapsulate the whole configuration file with a test.. just so it will only be executed if it is running in the context of a platform.sh instance. Just so we are polite and not interfere with your local setup. We could have tested here for any other platform environment variable such as PLATFORM_APPLICATION_NAME
