### ISSUE TITLE
Type in Symfony URL

### ISSUE THREAD

**Issue by weaverryan** [platformsh/platformsh-examples#79]
The URL to the Symfony repository has a typo at the end - it ends in `symfont` instead of `symfony`.

Also, as this was my first time to this page, I was confused at first by the `[DEPRECATED]` stuff. Are you linking me to a deprecated repository? Eventually, I actually read more (of course, we don't read at first) and saw that there *were* branches for Symfony and Drupal, but now they have their own repositories. Maybe not mention the "branches" stuff at all, and instead just have a nice list with URLs to all of the examples that are supported. If some go to branches on this repo, cool :).

Cheers - I'm excited to test things out for my own project.

**Comment by sruggier** [comment]
Thanks for reporting this! I've fixed the typo and updated the wording around those links to hopefully be less confusing.
